spring:
    session.jdbc.initialize-schema: always
    datasource:
        url: 'jdbc:oracle:thin:@localhost:1521:XE'
        username: 'my_db'
        password: 'shashi'
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        database: oracle
    security:
      user:
        name: 'shashi'
        password: 'shashi'


wishcart:
    dbdetails:
        #driver-class-name: 'oracle.jdbc.driver.OracleDriver'
        url: 'jdbc:oracle:thin:@localhost:1521/XE'
        username: 'my_db'
        password: 'shashi'
        dataSourceProperties:
          maximumPoolSize: 10
          minimumIdle: 2
          cachePrepStmts: true
          prepStmtCacheSize: 256
          prepStmtCacheSqlLimit: 2048
          seServerPrepStmts: true



#wishcart:
    #http:
        #version:
    #cache:
        #hazelcast:
            #time-to-live-seconds: 3600
            #backup-count: 1
            #management-center:
                #enabled: false
                #update-interval: 3
                #url: http://localhost:8180/mancenter















logging:
    level:
        org.hibernate.SQL: debug