server:
    port: 8443
    servlet:
        context-path: '/api'


management:
    sever:
        port: '8443'
    #security:
        #enabled: false

spring:
    datasource:
        url: 'jdbc:oracle:thin:@localhost:1521:XE'
        username: 'my_db'
        password: 'shashi'
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
        database: oracle
    user:
        name: 'shashi'
        password: 'shashi'
    #security:
        #enabled: false
    application:
        name: Wishcart

wishcart:
    dbdetails:
        #driver-class-name: 'oracle.jdbc.driver.OracleDriver'
        url: 'jdbc:oracle:thin:@localhost:1521/XE'
        username: 'my_db'
        password: 'shashi'
        dataSourceProperties:
          maximumPoolSize: 10
          minimumIdle: 2
          cachePrepStmts: true
          prepStmtCacheSize: 256
          prepStmtCacheSqlLimit: 2048
          seServerPrepStmts: true
   #async:
        #core-pool-size: 2
        #max-pool-size: 50
        #queue-capacity: 10000
        # By default CORS is disabled. Uncomment to enable.
        #cors:
            #allowed-origins: "*"
            #allowed-methods: "*"
            #allowed-headers: "*"
            #exposed-headers: "Link,X-Total-Count"
            #allow-credentials: true
            #max-age: 1800
    #mail:
        #from: wish-cart@localhost
        #swagger:
            #default-include-pattern: /api/.*
            #title: Wish Cart API
            #description: Wish-Cart API documentation
            #version: 0.0.1
            #terms-of-service-url:
            #contact-name:
            #contact-url:
            #contact-email:
            #license:
            #license-url:
        #ribbon:
            #display-on-active-profiles: dev
